name: BYETZ
options:
  bundleIdPrefix: com.byetz
  deploymentTarget:
    iOS: "17.0"
targets:
  BYETZ:
    type: application
    platform: iOS
    sources:
      - BYETZApp.swift
      - ContentView.swift
      - Models
      - Services
      - Utilities
      - ViewModels
      - Views
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.byetz.BYETZ
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1"
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
      INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    info:
      path: Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UILaunchScreen: {}
